### ISSUE TITLE
no "now" equiv for HOTP

### ISSUE THREAD

**Issue by alystair** [Spomky-Labs/otphp#105]
| Q                    | A
| -------------------- | -----
| Bug report?          | yes
| Feature request?     | yes
| BC Break report?     | no
| RFC? / Specification | no
| Library version      | 10.0

How exactly is one supposed to get the output of a HOTP at a specific counter # before verification?
Use case: User sets up TOTP in Authenticator - but have the backup HOTP code sent to them via email or displayed on screen to be saved in whichever manner they choose.

**Comment by alystair** [comment]
Ok so I figured it out by looking at the source code - you add the `$hotp->at(counter)` to the documentation so others can figure it out quickly :)

**Comment by Spomky** [comment]
There is no `now` method for HOTP scheme because there is no timestamp involved in the digits computation.
Let say you have the following provisioning URI : `otpauth://hotp/My%20Service%3Aalice%40google.com?issuer=My%20Service&secret=JBSWY3DPEHPK3PXP&counter=0`.

QRCode is ![QRCode](http://api.qrserver.com/v1/create-qr-code/?data=otpauth%3A%2F%2Fhotp%2FMy%2520Service%253Aalice%2540google.com%3Fissuer%3DMy%2520Service%26secret%3DJBSWY3DPEHPK3PXP%26counter%3D0)

The counter is `0` on server and application sides.
The application gives you the following digits: 282760.
Each time you ask for digits, the counter on application side increases.
Next digits are 996554.

You can verify these digits using the `verify` method.

```php
use OTPHP\Factory;

$otp = Factory::loadFromProvisioningUri('otpauth://hotp/My%20Service%3Aalice%40google.com?issuer=My%20Service&secret=JBSWY3DPEHPK3PXP&counter=0');
$otp->verify('282760');
```
Each time an OTP is verified, the counter increases as well. The actual provisioning URI is now `otpauth://hotp/My%20Service%3Aalice%40google.com?issuer=My%20Service&secret=JBSWY3DPEHPK3PXP&counter=1`.

But the counters may be out of sync e.g. when you ask for several digits on the application side or if an OTP is verified on server side using another application.
In this case, it is recommended to use the `window` parameter. This will allow the verification of the digits at the actual counter and the next ones.

In the following example, the counter on application side is 100 and on server side is 80.

```php
use OTPHP\Factory;

$otp = Factory::loadFromProvisioningUri('otpauth://hotp/My%20Service%3Aalice%40google.com?issuer=My%20Service&secret=JBSWY3DPEHPK3PXP&counter=8');
$otp->verify(
    '123456',  // The digits to verify
    null,      // Start at the actual counter
    30         // Also verify with the 30 next counters
);
```

When verified, the counter on server side is updated. Now the counter is 101.

I will add some words in the documentation.

**Comment by Spomky** [comment]
Closign as answered. The documentation will be updated accordingly.
Feel free to open it again if needed.

**Comment by grimxd** [comment]
The `$hotp->at(counter)` helped me too. I needed a way to generate the current hotp code (without third party app) but it is not specified in the documentation.
