### ISSUE TITLE
TOTP code randomly incorrect

### ISSUE THREAD

**Issue by whitsey** [Spomky-Labs/otphp#223]
### Version(s) affected

^10.0

### Description

Intermittently, every 10-15 logins, the code generated by the chosen TOTP app gets rejected.
Generally if I try again it will work if not the 2nd time, definitely the 3rd time.
App returns false when matching entered TOTP code from app with $totp->now()

### How to reproduce

It is random - not regularly but every so often it just returns false when matching code with $totp->now()

**Comment by Spomky** [comment]
Hi,

Can you share more information on this issue?
In particular, do you have a code sample to figure out what is going on?
Do you use the window?

**Comment by whitsey** [comment]
Hi, 

I use a text field to capture the code (don't know about "the window") and pass it to: 


    function validate2fa($user_id, $authcode) {

		$query = "SELECT secret FROM Users_2fa WHERE user_id='".$user_id."'";
		
		if( $result = mysqli_query( $this->mysqli, $query ) )
		{
			$row = mysqli_fetch_assoc( $result );

			$totp = TOTP::create($row['secret']);
			$totp->setLabel('Login'); 
			$totp->setIssuer('ABC');
			
			if ( $authcode == $totp->now() )
			{
				return true;
			}
			else 
			{
				return false;
			}
		}
		else
		{
			return false;
		}

	}

**Comment by Spomky** [comment]
The following code should work.
I use the method `verify` instead of comparison. The latter is not constant-time safe.
The boolean can be returned directly and I simplified a few lines (label ir issuer are not needed for the verification).
EDIT: I changed the DB query to avoid SQL injection.

The `window` (third argument = `10`) allows verification with a 10-second time drift.
This feature allows the user to get the auth code, go back to the input, and validate it.
It is a good practice to use it and avoid rejection because the auth code expired 1 or 2 seconds before.
To me, this is exactly what happens in your case.

```php
function validate2fa($user_id, $authcode)
{
	$query = $this->mysqli->prepare("SELECT secret FROM Users_2fa WHERE user_id = ?");
	$query->bind_param("i", $user_id); // "i" if the user ID is an integer, "s" if a string
	$query->execute();
	$result = $query->get_result();
	$query->close();
	$row = $result->fetch_assoc();
	if (!$row) {
		return false;
	}
	$totp = TOTP::create($row['secret']);

	return $totp->verify($authcode, null, 10);
}
```

**Comment by whitsey** [comment]
Perfect. Makes sense.
Updated in code though and created more problems.
I changed the window to 3 and it has been a little more stable - 10 must've been too long for me (who had it ready to go when testing)
