### ISSUE TITLE
TOTP verify is failing suddenly

### ISSUE THREAD

**Issue by mattcheww** [Spomky-Labs/otphp#63]
I'm stuck with an issue where my two factor authentication isn't able to verify codes anymore. I had successfully integrated the package with Laravel 5.3 and it was working wonderfully. I came back to my computer this morning and am unable to login without manually disabling the two factor system.

I can't think of anything I changed that would have broken the two factor system. After manually disabling the two factor for the account, I went back to set up 2fa for that account. I wasn't even able to get the initial check to go through. And I know I hadn't changed and of those files.

Here is the code to validate my 2fa input:

```
    public function enableTwoFactor(Request $request) {
        $user = Auth::user();

        $label = $user->email;
        $secret = Base32::encode($user->secret);

        $totp = new TOTP(
            $label,
            $secret,
            30,
            'sha1',
            6   
        );

        $check = $totp->verify($request->code);

        if ( $check ) {
            $user->enable_2fa = 1;
            $user->backup_codes = $this->generateBackupCodes();
            $user->save();
        }

        return redirect('/account/2fa');
    }
```

The information that is passed into the barcode is the same code shown above. I can't seem to see any reason for the code not to successfully verify anymore.

Am I trying to verify the 2fa code correctly? Or has there recently been a change to how 2fa codes are verified that would cause this to no longer verify correctly?

Let me know if you need any more information.

Thank you

**Comment by Spomky** [comment]
Hi,

Thank you for reporting my this issue.

I have some questions that should help me to understand what is going on:

- Can you execute the following command line and tell me the version of the library you are using `composer info spomky-labs/otphp`?
- Is `$user->secret` a secret dedicated to 2fa or the secret used by the user to authenticate?

**Comment by mattcheww** [comment]
I am currently using version 8.3.0.

The `$user->secret` was created specifically for 2fa. I have been using this to generate a secret for users that don't already have one: `$user->secret = str_random(20);` Other than that it serves no purpose to regular user authentication.

**Comment by Spomky** [comment]
The application seems to be correctly configured with the QRCode. I do not think the issue comes from the application, however and if not already done, you may try to get the QRCode using the `getQrCodeUri` method (introduced in the `v8.0`).

A discrepancy may exist between the server timestamp and the application one. I recommend you to use the `window` parameter with the method `verify`: `$check = $totp->verify($request->code, null, 1);` (`1` means it will check the OTP at timestamp, during the last period and during the next one). You may increase that number during your tests.

As explained in [this wiki page](https://github.com/Spomky-Labs/otphp/wiki/What-should-I-store-in-my-server-database), I recommend to store the whole provisioning Uri and not the secret. Your code will look like the following one;

```php
<?php

use OTPHP\Factory;

public function enableTwoFactor(Request $request) {
	$user = Auth::user();
	$provisioningUri = $user->getProvisioningUri(); // Method/Property to be implemented

	$totp = Factory::loadFromProvisioningUri($provisioningUri);

	$check = $totp->verify($request->code, null, 1); // Verification with window parameter

	if ( $check ) {
		$user->enable_2fa = 1;
		$user->backup_codes = $this->generateBackupCodes();
		$user->save();
	}

	return redirect('/account/2fa');
}
```

**Comment by mattcheww** [comment]
Sorry about the delay in responding.

I finally got around to look around with this issue again, and it seems to be working fine now. I'm honestly not sure what was causing the verification of the codes to fail.
